"""empty message

Revision ID: 0be242a800b4
Revises: 8f010940ce58
Create Date: 2024-03-23 16:56:47.574541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be242a800b4'
down_revision = '8f010940ce58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('victor', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combats', schema=None) as batch_op:
        batch_op.drop_column('victor')

    # ### end Alembic commands ###
