"""empty message

Revision ID: 28bb08ffa851
Revises: aed88b9cd30d
Create Date: 2024-03-25 16:30:29.472174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28bb08ffa851'
down_revision = 'aed88b9cd30d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('techs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unlocked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('techs', schema=None) as batch_op:
        batch_op.drop_column('unlocked')

    # ### end Alembic commands ###
