"""empty message

Revision ID: 48613911eb23
Revises: 6da628492977
Create Date: 2024-03-17 18:04:55.339238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48613911eb23'
down_revision = '6da628492977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_next', sa.Boolean(), nullable=True))
        batch_op.drop_column('players_turn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('players_turn', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('player_next')

    # ### end Alembic commands ###
