"""empty message

Revision ID: 6da628492977
Revises: 27886fbfee9c
Create Date: 2024-03-16 16:17:48.520362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da628492977'
down_revision = '27886fbfee9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turn', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('players_turn', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combats', schema=None) as batch_op:
        batch_op.drop_column('players_turn')
        batch_op.drop_column('turn')

    # ### end Alembic commands ###
