"""empty message

Revision ID: 8f010940ce58
Revises: 8f4fc787ebd3
Create Date: 2024-03-23 16:29:59.520727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f010940ce58'
down_revision = '8f4fc787ebd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enemy_action', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combats', schema=None) as batch_op:
        batch_op.drop_column('enemy_action')

    # ### end Alembic commands ###
