"""empty message

Revision ID: ec21849a6420
Revises: f91de9baed6c
Create Date: 2024-03-16 10:42:37.263706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec21849a6420'
down_revision = 'f91de9baed6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('known_techs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_known_techs_character_id_characters', type_='foreignkey')
        batch_op.drop_constraint('fk_known_techs_tech_id_techs', type_='foreignkey')
        batch_op.drop_column('tech_id')
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('known_techs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('tech_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_known_techs_tech_id_techs', 'techs', ['tech_id'], ['id'])
        batch_op.create_foreign_key('fk_known_techs_character_id_characters', 'characters', ['character_id'], ['id'])

    # ### end Alembic commands ###
