"""empty message

Revision ID: f91de9baed6c
Revises: 9199e678a11d
Create Date: 2024-03-14 09:39:06.198595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91de9baed6c'
down_revision = '9199e678a11d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('techs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modifier', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('techs', schema=None) as batch_op:
        batch_op.drop_column('modifier')

    # ### end Alembic commands ###
